config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'schools#index'
  # resources :school, only: :destroy
  resources :schools do
    resources :groups, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :school
end

app/models/school.rb
class School < ApplicationRecord
  has_many :groups, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :set_group, only: :destroy

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.school_id = params[:school_id]
    if @group.save
      redirect_to school_path(params["school_id"])
    else
      render :new
    end
  end

  def destroy
    @group.delete
    redirect_to school_path(params["school_id"])
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: %i[edit show destroy update]

  def index
    @schools = School.all
  end

  def show
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)
    if @school.save
      redirect_to schools_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @school.update(school_params)
      redirect_to school_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @school.delete
    redirect_to schools_path
  end

  private

  def set_school
    @school = School.find(params[:id])
  end

  def school_params
    params.require(:school).permit(:name, :address, :city)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/views/groups/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to root_path do %>
    <%= image_tag("cropped-logo_eleva.png", size: "100x100", class: "img") %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      </li>
    </ul>
    <%= link_to "Voltar", school_path(params["school_id"]), class: "btn btn-outline-primary" %>
  </div>
</nav>

<%= simple_form_for @group, url: school_groups_path(params["school_id"], @group) do |f| %>
  <%= f.input :name, label: false, placeholder: "Nome da turma" %>
  <%= f.button :submit, "Adicionar", class: "btn btn-outline-secondary" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container d-flex justify-content-between align-items-center">
    <%= image_tag("logo-mobile-rodape.png", size: "150x150", class: "img") %>
    <p class="m-5">
      <span class="text-white" id="banner-typed-text"></span>
    </p>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStackCaseEleva1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/school/index.html.erb
<h1>index</h1>

<ul>
  <% @schools.each do |school| %>
  <%= link_to school_path(school) do%>
    <li> <%= school.name %> </li>
    <% end %>
  <% end %>
</ul>

app/views/schools/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to root_path do %>
    <%= image_tag("cropped-logo_eleva.png", size: "100x100", class: "img") %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      </li>
    </ul>
    <%= link_to "Voltar", school_path(@school), class: "btn btn-outline-primary" %>
  </div>
</nav>

<%= simple_form_for @school do |f| %>
  <%= f.input :name, label: false, placeholder: "Nome da escola" %>
  <%= f.input :address, label: false, placeholder: "Endereço" %>
  <%= f.input :city, label: false, placeholder: "Cidade" %>
  <%= f.button :submit, "Salvar", class: "btn btn-outline-secondary" %>
<% end %>

app/views/schools/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to root_path do %>
    <%= image_tag("cropped-logo_eleva.png", size: "100x100", class: "img") %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      </li>
    </ul>
    <%= link_to "Nova escola", new_school_path, class: "btn btn-outline-primary" %>
  </div>
</nav>

<div class="grid">
  <% @schools.each do |school| %>
  <%= link_to school_path(school) do%>
  <div class="card card-grow">
      <div class="card-body">
        <h5 class="card-title"><%= school.name %></h5>
        <p class="card-text"><%= school.address %>, <%= school.city %></p>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/schools/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to root_path do %>
    <%= image_tag("cropped-logo_eleva.png", size: "100x100", class: "img") %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      </li>
    </ul>
    <%= link_to "Voltar", schools_path, class: "btn btn-outline-primary" %>
  </div>
</nav>

<%= simple_form_for @school do |f| %>
  <%= f.input :name, label: false, placeholder: "Nome da escola" %>
  <%= f.input :address, label: false, placeholder: "Endereço" %>
  <%= f.input :city, label: false, placeholder: "Cidade" %>
  <%= f.button :submit, "Adicionar", class: "btn btn-outline-secondary" %>
<% end %>

app/views/schools/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to root_path do %>
    <%= image_tag("cropped-logo_eleva.png", size: "100x100", class: "img") %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Adicionar turma", new_school_group_path(@school), class: "dropdown-item" %>
      </li>
      <li class="nav-item">
        <%= link_to "Editar escola", edit_school_path, class: "dropdown-item" %>
      </li>
      <li class="nav-item">
        <%= button_to 'Excluir escola', school_path(@school), class: "dropdown-item", method: :delete, data: {confirm: "Tem certeza?"} %>
      </li>
      <li class="nav-item">
        <%= link_to "Voltar", root_path, class: "dropdown-item" %>
      </li>
    </ul>
  </div>
</nav>

<h2 class="mb-4"> Colegio: <%= @school.name %> </h2>

<div class="grid">
  <% @school.groups.each do |group| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title text-center"><%= group.name %></h5>
        <%= button_to 'Deletar turma', school_group_path(@school, group), class: "btn btn-sm btn-outline-danger",method: :delete, data: {confirm: "Tem certeza?"} %>
      </div>
    </div>
  <% end %>
</div>